### ISSUE TITLE
Can the rule "Only top-level calls to a define function will be transformed" be relaxed?

### ISSUE THREAD

**Issue by bschlenk** [msrose/babel-plugin-transform-amd-to-commonjs#38]
I'm porting a requriejs app over to webpack, and it pulls in jquery-ui. Jquery-ui used a module shim that [calls define within another function](https://github.com/jquery/jquery-ui/blob/master/ui/widget.js#L16-L26).

```js
( function( factory ) {
	if ( typeof define === "function" && define.amd ) {

		// AMD. Register as an anonymous module.
		define( [ "jquery", "./version" ], factory );
	} else {

		// Browser globals
		factory( jQuery );
	}
}( function( $ ) {
```

Is there a way to make this babel plugin transform the define call into a require call?

**Comment by msrose** [comment]
Thanks for the issue @bschlenk.
I thought about this in the early days of the plugin but had no use case for it until now. 

Note that webpack does support transforming amd to commonjs by default (no plugin required), so I'm guessing you need it in a test environment?

My thoughts for supporting non-top level defines without breaking changes are to provide it as an extra setting that can be configured in .babelrc, so the config would look like:
```
{
    "plugins": [["transform-amd-to-commonjs", { "restrictToTopLevelDefine": false }]]
}
```
where the default config would be true.

But even with that change, I think with this specific example that you would currently get something like
```
require('jquery');
require('./version');
module.exports = factory;
```
since the factory passed in is a variable, not a function literal, which the plugin does not currently support, and is not trivial to fully implement without assuming that the variable represents a function (it could be literally anything since AMD supports define-ing modules with non-function factories, e.g. config objects).

**Comment by bschlenk** [comment]
That is correct, I'm trying to run the tests through jest which doesn't do the same transpilation that webpack does. The build with webpack works fine.

It does seem like a very hard problem to solve, since you'd have to see exactly where the factory was coming from to know that it was a function.

Perhaps there is a better solution? Maybe a better question for jest or webpack, but do you know if I can have my jest tests run after webpack? Then I wouldn't have to rely on babel to translate the tests into something that jest understands.

**Comment by msrose** [comment]
I have heard of some plugins that will run jest on the webpack build, but i don't know of any in particular to recommend.

I have a few ideas, so I'm going to do some more investigation into what it would take to support modules defined like jquery ui. I'll create some separate issues since I think there's a couple different factors at play to get it working. It's something cool to support but in terms of a interim solution for your case I don't have any other ideas...

**Comment by bschlenk** [comment]
I actually added support to webpack for arrow functions in AMD modules, so I can tell you a little bit about how webpack does it. If I remember correctly, they wrap the entire module in an IIFE and pass in their own define method. That way you can do a typeof check on the factory at runtime to see if it is a function, and call it with the required modules.

**Comment by msrose** [comment]
Ah great, good to know! Yeah I figured a runtime check would be the only way to be completely correct with it, so that's the route I'll probably take. Although it's unfortunate that with the current plugin strategy, it complicates the output of non-function factories significantly. e.g. `define({ config: 'object' })` goes from just `module.exports = { config: 'object' }` to something much more unwieldy, especially if there's a dependency list as well. Depending on how how complicated the changes are, it might be better to pivot to a custom define method that gets injected into modules instead, as you alluded to.

**Comment by msrose** [comment]
Going to restrict this thread to discussion only for non-top-level define support, any other info about runtime checks for functions on non-function literal AST nodes can go in #39 :)

**Comment by msrose** [comment]
Addressed by #43

**Comment by jdmerinor** [comment]
I'm actually having the same issue and I was wondering how did you actually managed to get rid of the:
` typeof define === "function" && define.amd`
 check, because even though the plugin is now replacing the define call with a require it won't really go inside once it's running due to this check?

**Comment by msrose** [comment]
Hm so you should be able to inject a `define` function into your environment separately to get around that issue. For example in your test setup file:

```
global.define = function() {}
global.define.amd = true
```

The plugin will transform all calls to define so this won't affect any code that calls the function.

Haven't tested this directly so please let me know if it works, and I'll do some more digging/documenting if necessary.
